<?php

return [

    /*
    |----------------------------------------------------------------------
    | Generate routes
    |----------------------------------------------------------------------
    |
    | All resources must have it's own routes defined. This can be attached
    | to a controller or closure. When this is set the true, it will add a
    | special route that should cover all restful resource actions.
    |
    | The use of this is recommended for development, since you only have to
    | define and setup your resources. For production you have to take security
    | in account, else your API MIGHT be not secured.
    |
    */

    'generate' => true,

    /*
    |----------------------------------------------------------------------
    | Generate routes for related resources
    |----------------------------------------------------------------------
    |
    | When the routes are automatically generated by GSR, it binds the basic
    | REST urls for each resources. The following are bound:
    |   - [GET]    /items
    |   - [POST]   /items
    |   - [GET]    /items/5
    |   - [PUT]    /items/5
    |   - [DELETE] /items/5
    |
    | But, often you find yourself need a list of resources from a relation.
    | Within the REST principles it is possible. The urls that will be bound are:
    |   - [GET] /items/5/sub-items
    |   - [GET] /items/5/sub-items/10
    |
    | So this actually switches the sub-items on, or off.
    | Note, only GET routes are bound since you already have the id when executing
    | other actions.
    |
    */

    'relations' => true,

    /*
    |----------------------------------------------------------------------
    | Routes settings
    |----------------------------------------------------------------------
    |
    | When generating the resource routes Get Some Rest will apply the code.
    | Here you can define some settings that will be passed to the router->group
    | method. You can set a prefix, add middleware or set other settings.
    |
    */

    'settings' => [
        'prefix' => 'api/v1'
    ],
    
    /*
    |----------------------------------------------------------------------
    | Resource routes controller
    |----------------------------------------------------------------------
    |
    | When generating the resource routes Get Some Rest will apply the code.
    | Here you can define which controller it should use. Note that this
    | controller MUST discover the target resource by itself, not the URL.
    | This is because the resource name, in the url, is a variable and can be
    | different each call.
    |
    */

    'controller' => 'Peakfijn\GetSomeRest\Http\Controllers\RestController',

];
